language: python
python:
  - "2.7"

addons:
  apt:
    packages:
      - python-flake8

script:
  # TODO: fix these remaining style check issues
  - flake8 --ignore=W191,W601,E126,E261,E265,E266,E501 .
  - flake8 --ignore=F401,F403,F405,W191,E126,E128,E265,E266,E402,E501,E702,E703 yagv
